FROM asurin/httpd-mariadb
MAINTAINER Qiao Qiao "qiaozha@gmail.com"


RUN yum install -y php php-mysql php-gd php-ldap php-odbc php-pear php-xml php-xmlrpc php-mbstring php-soap curl curl-devel

CMD ["/run.sh"]

